name: ChromiumGUI
version: '${project.version}'
main: me.chromisek.chromiumGUI.ChromiumGUI
api-version: '1.21'
authors: [ Chromisek ]
description: GUI plugin navazajici na ChromiumCore
depend: [ChromiumCore]
softdepend: [spark, "PlaceholderAPI"]
load: POSTWORLD
commands:
  chromium:
    description: Hlavní příkaz pro ChromiumGUI.
    usage: /<command> [gui|reload|version|help]
  gui:
    description: Otevře hlavní panel ChromiumGUI.
    usage: /<command>
    aliases: [cgui]