name: ChromiumGUI
version: '1.0-SNAPSHOT'
main: me.chromisek.chromiumGUI.ChromiumGUI
api-version: '1.21'
authors: [ Chromisek ]
description: GUI plugin navazajici na ChromiumCore
depend: [ChromiumCore]

commands:
  chromium:
    description: Hlavní příkaz pro ChromiumGUI.
    usage: /<command> [gui|reload|version|help]
    aliases: [cgui, gui]